<ul class="main-nav">
    <li id="about-header" class="item--to-show"><a href="#about">About</a></li>
    <li><a href="#contribute">Contribute</a></li>
    <li class="item--to-show"><a href="#team">Team</a></li>
    <li class="item--to-show"> <a href="/docs">Overview</a></li>
    <li class="item--to-show"> <a href="https://our.status.im/tag/nimbus/">News</a> </li>
    <li class="item--to-show"> <a href="https://subscribe.nimbus.team/">Newsletter</a> </li>
</ul>
