<ul class="main-nav">
    <li id="about-header" class="item--to-show"><a href="https://dev-nimbus.status.im/#about" class="">About</a></li>
    <li><a href="https://dev-nimbus.status.im/#contribute">Contribute</a></li>
    <li class="item--to-show"><a href="https://dev-nimbus.status.im/#team">Team</a></li>
    <li class="item--to-show"> <a href="/docs">Docs</a></li>
    <li class="item--to-show"> <a href="https://our.status.im/tag/nimbus">Blog</a> </li>
</ul>