<ul class="main-nav">
    <li class="item--to-show"><a href="https://status.im/get" class="">App</a></li>
    <li class="item--to-show"> <a href="https://our.status.im/">Blog</a> </li>
    <li class="item--to-show"> <a href="https://status.im/docs">Docs</a></li>
    <li class="item--dropdown item--dropdown-projects"> <a href="#" class="">Projects</a></li>
    <li><a href="https://status.im/contribute">Contribute</a></li>
    <li class="item--dropdown"><a href="#" class="item--dropdown-community">Community</a></li>
    <li class="item--more"><a href="#" class="item--more">More</a></li>
</ul>