<!-- GitHub star -->
<a class="github-button" href="https://github.com/status-im" data-icon="octicon-star" data-show-count="true" aria-label="Star status-im on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/status-im/nimbus/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork status-im/status-react on GitHub">Fork</a><!-- Tweet button -->
<!-- Twitter follow button -->
<a href="https://twitter.com/ethstatus" class="twitter-follow-button" data-show-count="true">Follow @ethstatus</a>
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Twitter share button -->
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
